### ISSUE TITLE
Create Infrastructure

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/docs.skale.network#130]
```[tasklist]
## Todo
- [x] Create Top Level Folder
- [x] Basic Intro Page of Available Infrastructure
- [x] Update *Playbook.yml
```
