### ISSUE TITLE
Move sFUEL Api Distribution Recipe to Infra

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/docs.skale.network#132]
```[tasklist]
### todos
- [x] Move API Distribution to Infra Category
- [x] Edit content to remove recipes
```

```[tasklist]
### verifications
- [x] Add Page alias
```
