### ISSUE TITLE
Migrate Tools to Top Level Category

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/docs.skale.network#137]
```[tasklist]
### TODO
- [ ] Migrate All Tools to Top Level Category
- [ ] Create Tools Landing Page
- [ ] Categorize Tools
- [ ] Create Sub Navigation
- [ ] Create Yaml file for tools only
- [ ] Add watch command for tools only
```

```[tasklist]
### Validate
- [ ] Validate Page Aliases
- [ ] Confirm Subcategories
```
