### ISSUE TITLE
[Config] Setup Migration to Vercel

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/docs.skale.network#83]
```[tasklist]
## Todos
- [x] Add vercel.json
- [x] Setup redirect for initial landing page
- [x] Add clean urls
```
