### ISSUE TITLE
[Develop | Update] Minor Updates Develop Landing Page

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/docs.skale.network#90]
```[tasklist]
## TODO - Mandatory
- [x] Cleanup Get a SKALE Endpoint Headers [all capital first words instead of mixed]
- [x] Add a header before the video ```Add SKALE Chaos Testnet to Metamask```
- [x] Add hardhat to Developer Tool Docs List
- [x] New dApps -> Minor paragraph with link to recipes
```
