### ISSUE TITLE
[Landing Page | Content] Minor Content Updates & Additions to Landing Page

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/docs.skale.network#91]
```[tasklist]
### TODOs
- [x] Add Build on SKALE - Box No.1
- [x] Add Developer Recipes - Box No.2
- [x] Rearrange Box Links - See Proposed Layout Below
- [x] Update Language According to Finalized Language Tweaks
- [x] Remove last link on page [broken link]
```

Proposed Layout
---

[0, 1, 2]
[3,4,5]
[6,7,8]

Row 1: Build on SKALE, Developer Recipes, SKALE Chain
Row 2: IMA, Metaport, Filestorage
Row 3: SKALE Technology, Validators, Delegation

Proposed Language Tweaks
---
> Shared tweak is to remove all periods from descriptions

_**[Format = Index - Title - Description]**_
0 - Build on SKALE - Building in Web3 has never been easier
1 - Developer Recipes - Guided tutorials to help you unlock the power of SKALE
2 - SKALE Chain - Learn about the technology powering the network
3 - IMA - The Interchain Messaging Agent facilitates the Ethereum - SKALE Bridge
4 - Metaport - The UI Widget built to enhance IMA integration
5 - Filestorage - A Web3 storage layer available on each chain
6 - SKALE Technology - Deep dive into the technology
7 - Validators - Run SKALE Nodes to support the SKALE Network
8 - Delegation - Delegate SKL tokens to validators

**Comment by TheGreatAxios** [comment]
sFUEL Replaces Delegation
